### ISSUE TITLE
How to include beats % along with the response

### ISSUE THREAD

**Issue by pranavmappoli** [JeremyTsaii/leetcode-stats-api#2]
How we can get the beats % on each section as we can see in the leetcode profile. also details of badge etc

**Comment by JeremyTsaii** [comment]
To find this out, you can go to the Networks tab of the Chrome developer tools and see what the GraphQL queries look like.

For example, I found this query to work for the beats % of each section:

```
query getUserProfile($username: String!) {
  matchedUser(username: $username) {
    problemsSolvedBeatsStats {
        difficulty
        percentage
    }
  }
}
```
