### ISSUE TITLE
Application error is shown when try to access URL

### ISSUE THREAD

**Issue by fabasoad** [JeremyTsaii/leetcode-stats-api#3]
## Steps to reproduce

1. Open browser
2. Go to `https://leetcode-stats-api.herokuapp.com/<YOUR USERNAME>`
3. See the page

## Expected behavior

Stats should be shown

## Actual behavior

Application error is shown:

![Screen Shot 2022-12-03 at 18 17 25](https://user-images.githubusercontent.com/2127723/205433714-658708fe-6e11-4594-b9dc-bbbfd1c292e5.png)

**Comment by JeremyTsaii** [comment]
Thanks for the notice. This is caused by the ending of free heroku plans, am spinning it back up now.
